pain_dictionary = {
'abdomen discomfort (abdominal discomfort)':'abdominal pain',
'abdomen pain (abdominal pain)':'abdominal pain',
'abdominal back pain (abdominal pain through to back)':'abdominal pain',
'abdominal cramp (abdominal cramps)':'abdominal pain',
'abdominal cramping (abdominal cramps)':'abdominal pain',
'abdominal cramps':'abdominal pain',
'abdominal discomfort':'abdominal pain',
'abdominal discomfort (abdominal discomfort)':'abdominal pain',
'abdominal distress':'abdominal pain',
'abdominal pain':'abdominal pain',
'abdominal pain (abdominal pain)':'abdominal pain',
'abdominal pain nausea (nausea or abdominal pain)':'abdominal pain',
'abdominal pain symptoms (abdominal pain)':'abdominal pain',
'abdominal pain, (left lower quadrant pain)':'abdominal pain',
'abdominal pain, (left upper quadrant pain)':'abdominal pain',
'abdominal pain, (right lower quadrant pain)':'abdominal pain',
'abdominal pain, (right upper quadrant pain)':'abdominal pain',
'abdominal pain, crampy (abdominal cramps)':'abdominal pain',
'abdominal pain, epigastric (epigastric pain)':'abdominal pain',
'abdominal pain, left lower quadrant (left lower quadrant pain)':'abdominal pain',
'abdominal pain, left upper quadrant (left upper quadrant pain)':'abdominal pain',
'abdominal pain, right lower quadrant (right lower quadrant pain)':'abdominal pain',
'abdominal pain, right upper quadrant (right upper quadrant pain)':'abdominal pain',
'abdominal tenderness':'abdominal pain',
'acute abdominal pain':'abdominal pain',
'bowel angina (abdominal angina)':'abdominal pain',
'bowel pain (intestinal pain)':'abdominal pain',
'burning epigastric pain':'abdominal pain',
'chronic abdominal pain':'abdominal pain',
'diffuse abdominal pain':'abdominal pain',
'gas pain (abdominal wind pain)':'abdominal pain',
'gastrointestinal distress (distress gastrointestinal)':'abdominal pain',
'general abdominal pain (generalized abdominal pain)':'abdominal pain',
'gi distress (gastrointestinal irritation)':'abdominal pain',
'gi pain (gastrointestinal pain)':'abdominal pain',
'intermittent abdominal pain':'abdominal pain',
'intestinal angina (abdominal angina)':'abdominal pain',
'left lower quadrant pain':'abdominal pain',
'left side abdominal pain (left sided abdominal pain)':'abdominal pain',
'left sided abdominal pain':'abdominal pain',
'left upper quadrant pain':'abdominal pain',
'llq abdominal pain (left lower quadrant pain)':'abdominal pain',
'llq pain (left lower quadrant pain)':'abdominal pain',
'lower abdominal pain':'abdominal pain',
'luq pain (left upper quadrant pain)':'abdominal pain',
'non specific abdominal pain (abdominal pain)':'abdominal pain',
'nonspecific abdominal pain':'abdominal pain',
'pain left lower quadrant (left lower quadrant pain)':'abdominal pain',
'pains, abdominal (abdominal pain)':'abdominal pain',
'rebound tenderness':'abdominal pain',
'recurrent abdominal pain':'abdominal pain',
'right abdominal pain (right sided abdominal pain)':'abdominal pain',
'right lower quadrant pain':'abdominal pain',
'right sided abdominal pain':'abdominal pain',
'right upper quadrant abdominal tenderness':'abdominal pain',
'right upper quadrant pain':'abdominal pain',
'rlq abdominal pain (right lower quadrant pain)':'abdominal pain',
'rlq pain (right lower quadrant pain)':'abdominal pain',
'ruq abdominal pain (right upper quadrant pain)':'abdominal pain',
'ruq pain (right upper quadrant pain)':'abdominal pain',
'suprapubic pain':'abdominal pain',
'suprapubic pain (suprapubic pain)':'abdominal pain',
'upper abdominal pain':'abdominal pain',
'ache':'ache',
'aches (ache)':'ache',
'aching (ache)':'ache',
'aching pain (ache)':'ache',
'aching sensation (ache)':'ache',
'analgesia (absence of pain sensation)':'analgesia',
'arm discomfort':'arm pain',
'arm pain':'arm pain',
'arm pain (arm pain)':'arm pain',
'arm tightness (tightness in arm)':'arm pain',
'axilla pain (pain in axilla)':'arm pain',
'extremity pain, upper (arm pain)':'arm pain',
'forearm pain (pain in forearm)':'arm pain',
'left arm pain (pain in left arm)':'arm pain',
'pain in arm (arm pain)':'arm pain',
'pain in left arm':'arm pain',
'pain in right arm':'arm pain',
'pain radiating to left arm':'arm pain',
'pain radiating to right arm':'arm pain',
'pain right arm (pain in right arm)':'arm pain',
'right arm pain (pain in right arm)':'arm pain',
'right upper extremity pain (pain in right arm)':'arm pain',
'right upper extremity pain (pain of right arm only)':'arm pain',
'acute back pain':'back pain',
'acute thoracic back pain':'back pain',
'back ache (back pain)':'back pain',
'back discomfort (back distress)':'back pain',
'back mid pain (back pain mid back)':'back pain',
'back over pain (back pain)':'back pain',
'back pain':'back pain',
'back pain (back pain)':'back pain',
'back pain radiating (radiating back pain)':'back pain',
'back pain symptoms (back pain)':'back pain',
'back pain with radiation':'back pain',
'back pain, lower (low back pain)':'back pain',
'back pain, severe':'back pain',
'back pain, severe (severe back pain)':'back pain',
'back pain, upper (upper back pain)':'back pain',
'back severe pain (severe back pain)':'back pain',
'back tenderness':'back pain',
'back tenderness (back tenderness)':'back pain',
'backache (back pain)':'back pain',
'backpain (back pain)':'back pain',
'cervical spine pain (pain in cervical spine)':'back pain',
'chronic back pain':'back pain',
'dorsal back pain (back pain)':'back pain',
'dorsal pain (back pain)':'back pain',
'low back ache (low back pain)':'back pain',
'low back pain':'back pain',
'low back pain symptoms (low back pain)':'back pain',
'low backpain (low back pain)':'back pain',
'lower back pain (low back pain)':'back pain',
'lower backpain (low back pain)':'back pain',
'lumbar back pain (pain in lumbar spine)':'back pain',
'lumbar pain (low back pain)':'back pain',
'lumbar region pain (abdominal pain through to back)':'back pain',
'lumbar region pain (low back pain)':'back pain',
'lumbar spine pain (pain in lumbar spine)':'back pain',
'mid back pain (back pain mid back)':'back pain',
'pain in back (back pain)':'back pain',
'pain in cervical spine':'back pain',
'pain in spine':'back pain',
'pain in thoracic spine':'back pain',
'pain spine (pain in spine)':'back pain',
'pains, lower back (low back pain)':'back pain',
'posterior pain (back pain)':'back pain',
'radiating back pain':'back pain',
'sciatica':'back pain',
'sciatica (sciatica)':'back pain',
'spine pain (pain in spine)':'back pain',
'thoracic back pain':'back pain',
'thoracic spine pain (pain in thoracic spine)':'back pain',
'upper back pain':'back pain',
'bladder pain':'bladder pain',
'burning urination (scalding pain on urination)':'bladder pain',
'dysuria':'bladder pain',
'dysuria (dysuria)':'bladder pain',
'urination pain (dysuria)':'bladder pain',
'body ache (body pain)':'body pain',
'body pain':'body pain',
'body pains (body pain)':'body pain',
'whole body pain (total body pain syndrome)':'body pain',
'bone pain':'bone pain',
'bone pain (bone pain)':'bone pain',
'bone tenderness':'bone pain',
'bone tenderness (bone tenderness)':'bone pain',
'pain bone (bone pain)':'bone pain',
'pain femur (pain in femur)':'bone pain',
'breasts pain (mastodynia)':'breast pain',
'pain in the breast (mastodynia)':'breast pain',
'pain of breast (mastodynia)':'breast pain',
'painful breast (mastodynia)':'breast pain',
'persistent breast pain (persistent mastalgia)':'breast pain',
'tenderness of breasts (breast tenderness)':'breast pain',
'burning (burning sensation)':'burning',
'burning on urination (scalding pain on urination)':'burning',
'burning pain (pain, burning)':'burning',
'burning sensation':'burning',
'burning sensation (burning sensation)':'burning',
'burning sensations (burning sensation)':'burning',
'pain, burning':'burning',
'painful paresthesias':'burning',
'buttock pain (pain in buttock)':'buttock pain',
'calf muscle cramp (muscle cramps in the calf)':'calf pain',
'calf pain (pain in calf)':'calf pain',
'calf tenderness':'calf pain',
'pain in calf':'calf pain',
'bone metastatic pain (metastatic bone pain)':'cancer pain',
'cancer pain':'cancer pain',
'pain from metastases':'cancer pain',
'acute chest pain':'chest pain',
'acute respiratory distress':'chest pain',
'angina (angina pectoris)':'chest pain',
'angina chest pain (chest pain angina)':'chest pain',
'angina equivalent':'chest pain',
'angina pain (angina pectoris)':'chest pain',
'angina symptoms (angina symptom)':'chest pain',
'anginal equivalent (angina equivalent)':'chest pain',
'anginal equivalents (angina equivalent)':'chest pain',
'anginal pain (angina pectoris)':'chest pain',
'anterior chest pain (anterior chest wall pain)':'chest pain',
'anterior chest wall pain':'chest pain',
'anterior pleuritic chest pain (anterior pleuritic pain)':'chest pain',
'anterior thigh pain (thigh pain anterior)':'chest pain',
'ards (respiratory distress syndrome, adult)':'chest pain',
'atypical chest pain':'chest pain',
'breath pain (chest pain on breathing)':'chest pain',
'breathing pain (chest pain on breathing)':'chest pain',
'burning chest (chest burning)':'chest pain',
'burning chest pain (chest burning pain of)':'chest pain',
'chest burning':'chest pain',
'chest burning pain of':'chest pain',
'chest discomfort':'chest pain',
'chest pain':'chest pain',
'chest pain (chest pain)':'chest pain',
'chest pain at rest':'chest pain',
'chest pain left side (left sided chest pain)':'chest pain',
'chest pain on exertion':'chest pain',
'chest pain radiating (radiating chest pain)':'chest pain',
'chest pain right side (right sided chest pain)':'chest pain',
'chest pain symptoms (chest pain)':'chest pain',
'chest pain, sharp':'chest pain',
'chest pain-l arm (left sided chest pain)':'chest pain',
'chest pressure':'chest pain',
'chest tightness':'chest pain',
'chest tightness/pressure (chest tightness or pressure)':'chest pain',
'chest wall pain':'chest pain',
'chronic chest pain':'chest pain',
'coronary angina (angina pectoris)':'chest pain',
'crushing chest pain':'chest pain',
'discomfort in chest (chest discomfort)':'chest pain',
'distressed respiratory (respiratory distress)':'chest pain',
'dull chest pain':'chest pain',
'esophageal chest pain':'chest pain',
'exercise-induced angina':'chest pain',
'exertion angina (exercise-induced angina)':'chest pain',
'exertional angina (exercise-induced angina)':'chest pain',
'exertional chest pain (chest pain on exertion)':'chest pain',
'feeling of chest tightness (chest tightness)':'chest pain',
'ischaemic chest pain (angina pectoris)':'chest pain',
'left lateral chest pain (left sided chest pain)':'chest pain',
'left sided chest pain':'chest pain',
'musculoskeletal chest pain':'chest pain',
'non-cardiac chest pain':'chest pain',
'other chest pain':'chest pain',
'pain breathing (chest pain on breathing)':'chest pain',
'pain in chest (chest pain)':'chest pain',
'pains, chest (chest pain)':'chest pain',
'pleuritic chest pain (pleuritic pain)':'chest pain',
'pleuritic pain':'chest pain',
'precordial pain':'chest pain',
'pressure in chest (chest pressure)':'chest pain',
'radiating chest pain':'chest pain',
'respiratory distress':'chest pain',
'respiratory pain (chest pain on breathing)':'chest pain',
'right chest pain (right sided chest pain)':'chest pain',
'right sided chest pain':'chest pain',
'thoracic pain (chest pain)':'chest pain',
'thorax pain (chest pain)':'chest pain',
'tightness in chest (chest tightness)':'chest pain',
'tightness of chest (chest tightness)':'chest pain',
'typical angina':'chest pain',
'typical anginal pain (typical angina)':'chest pain',
'upper chest pain':'chest pain',
'usual angina (typical angina)':'chest pain',
'distress':'distress',
'distress, respiratory (respiratory distress)':'distress',
'distressed (emotional distress)':'distress',
'fetal distress':'distress',
'upset (emotional distress)':'distress',
'ear pain (earache)':'ear pain',
'ear tenderness':'ear pain',
'otalgia (earache)':'ear pain',
'pain in ear (earache)':'ear pain',
'elbow pain (pain in elbow)':'elbow pain',
'epigastric ache (epigastric pain)':'epigastric pain',
'epigastric burning':'epigastric pain',
'epigastric discomfort':'epigastric pain',
'epigastric pain':'epigastric pain',
'epigastric tenderness':'epigastric pain',
'eye pain':'eye pain',
'eye pain (eye pain)':'eye pain',
'eye pain, severe':'eye pain',
'pain around eye':'eye pain',
'pain in eye (eye pain)':'eye pain',
'face pain (facial pain)':'facial pain',
'facial pain':'facial pain',
'pain in cheek':'facial pain',
'pain in face (facial pain)':'facial pain',
'finger pain (pain in finger)':'finger pain',
'pain of digit':'finger pain',
'thumb pain (pain in thumb)':'finger pain',
'flank pain':'flank pain',
'flank pains (flank pain)':'flank pain',
'flank tenderness (renal angle tenderness)':'flank pain',
'left flank pain':'flank pain',
'pain right flank (right flank pain)':'flank pain',
'right flank pain':'flank pain',
'side pain':'flank pain',
'burning feet':'foot pain',
'burning foot (burning feet)':'foot pain',
'foot pain':'foot pain',
'forefoot pain (pain of front foot of quadraped)':'foot pain',
'pain in foot (foot pain)':'foot pain',
'pain in left foot':'foot pain',
'gum pain (tenderness of gums)':'gum pain',
'gums pain (tenderness of gums)':'gum pain',
'hand pain':'hand pain',
'hands pain (hand pain)':'hand pain',
'pain in left hand':'hand pain',
'pain in right hand':'hand pain',
'bilateral headache':'headache',
'bsh (headache associated with sexual activity)':'headache',
'frequent headaches':'headache',
'frontal headache':'headache',
'frontal headaches (frontal headache)':'headache',
'head ache (headache)':'headache',
'head fullness (headache fullness)':'headache',
'head pressure (head pressure sensation)':'headache',
'headache (headache)':'headache',
'headache, occipital (occipital headache)':'headache',
'headache, recurrent (headache recurrent)':'headache',
'headache, severe (headache severe)':'headache',
'headaches (headache)':'headache',
'intermittent headache':'headache',
'morning headache':'headache',
'occipital headache':'headache',
'pain in head (headache)':'headache',
'persistent headache (headache persistent)':'headache',
'recurrent headaches (headache recurrent)':'headache',
'sharp headache':'headache',
'sinus headache':'headache',
'sinus pain':'headache',
'sinus pressure':'headache',
'throbbing headaches (throbbing headache)':'headache',
'vertex headache':'headache',
'cardiac angina (angina pectoris)':'heart pain',
'cardiac chest pain (cardiac pain)':'heart pain',
'cardiac pain':'heart pain',
'heart chest pain (cardiac pain)':'heart pain',
'heart pain (cardiac pain)':'heart pain',
'pain heart (cardiac pain)':'heart pain',
'heel pain':'heel pain',
'hernia pain':'hernia pain',
'hip pain':'hip pain',
'hip pain (hip joint pain)':'hip pain',
'hip pain (hip pain)':'hip pain',
'hips pain (hip pain)':'hip pain',
'ischia (sciatica)':'hip pain',
'ischial tuberosity tenderness':'hip pain',
'pain in buttock':'hip pain',
'pain in hip (hip pain)':'hip pain',
'pain in left hip':'hip pain',
'pain in pelvis (pelvic pain)':'hip pain',
'pain in right hip':'hip pain',
'right hip pain (pain in right hip joint)':'hip pain',
'right sided hip pain (pain in right hip)':'hip pain',
'sacral pain':'hip pain',
'incisional pain':'incisional pain',
'injections pain (pain during injection)':'incisional pain',
'jaw pain':'jaw pain',
'mandibular pain (jaw pain)':'jaw pain',
'mandibular pain (mandibular pain)':'jaw pain',
'pain in jaw (jaw pain)':'jaw pain',
'pain of jaw (jaw pain)':'jaw pain',
'pain radiating to jaw':'jaw pain',
'ankle joint pain (ankle pain)':'joint pain',
'ankle pain':'joint pain',
'arthralgia':'joint pain',
'arthralgias (arthralgia)':'joint pain',
'arthritic pain (arthritic pains)':'joint pain',
'joint ache (arthralgia)':'joint pain',
'joint pain (arthralgia)':'joint pain',
'joint pains (arthralgia)':'joint pain',
'joint soreness (joint tenderness)':'joint pain',
'joint tenderness':'joint pain',
'joint tenderness (joint tenderness)':'joint pain',
'mechanical pain':'joint pain',
'pain in joint (arthralgia)':'joint pain',
'pain in joints (arthralgia)':'joint pain',
'subtalar joint pain':'joint pain',
'arthralgia of knee (knee pain)':'knee pain',
'knee pain':'knee pain',
'knee pains (knee pain)':'knee pain',
'pain in ankle (ankle pain)':'knee pain',
'pain in knee (knee pain)':'knee pain',
'pain in left knee':'knee pain',
'pain in right knee':'knee pain',
'painful knee (knee pain)':'knee pain',
'extremities lower pain (lower extremity pain)':'leg pain',
'extremities pain (pain in limb)':'leg pain',
'ischemic pain':'leg pain',
'left leg pain (pain in left leg)':'leg pain',
'leg pain (pain in lower limb)':'leg pain',
'leg pain, nos (pain in lower limb)':'leg pain',
'limbs pain (pain in limb)':'leg pain',
'lower extremities pain (pain in lower limb)':'leg pain',
'lower extremity pain':'leg pain',
'pain in extremity (pain in limb)':'leg pain',
'pain in left leg':'leg pain',
'pain in leg (pain in lower limb)':'leg pain',
'pain in lower leg (pain in limb, lower leg)':'leg pain',
'pain in right leg':'leg pain',
'pain in right leg (pain in right lower limb)':'leg pain',
'pain in right lower limb':'leg pain',
'pain in right lower limb nos':'leg pain',
'pain in right thigh (pain of right thigh)':'leg pain',
'pain left leg (pain in left leg)':'leg pain',
'pain of right thigh':'leg pain',
'pain radiating to right leg':'leg pain',
'right leg pain (pain in right leg)':'leg pain',
'right leg pain (pain in right lower limb)':'leg pain',
'thigh pain':'leg pain',
'thigh pain (thigh pain)':'leg pain',
'upper extremity tenderness (tenderness of upper limb)':'leg pain',
'mild pain':'moderate pain',
'moderate pain':'moderate pain',
'pain, intractable':'moderate pain',
'cramp (muscle cramp)':'muscle pain',
'cramping (cramping sensation quality)':'muscle pain',
'cramping (muscle cramp)':'muscle pain',
'cramping legs (muscle cramps in leg)':'muscle pain',
'cramps (muscle cramp)':'muscle pain',
'crampy (cramping sensation quality)':'muscle pain',
'deltoid pain':'muscle pain',
'groin discomfort':'muscle pain',
'groin pain (inguinal pain)':'muscle pain',
'groin tenderness (groin tenderness)':'muscle pain',
'leg cramping (muscle cramps in leg)':'muscle pain',
'leg cramps (muscle cramps in leg)':'muscle pain',
'leg discomfort':'muscle pain',
'muscle ache (myalgia)':'muscle pain',
'muscle aches (myalgia)':'muscle pain',
'muscle cramping (muscle cramp)':'muscle pain',
'muscle cramps (muscle cramp)':'muscle pain',
'muscle discomfort (myalgia)':'muscle pain',
'muscle pain (myalgia)':'muscle pain',
'muscular pain (myalgia)':'muscle pain',
'myalgia':'muscle pain',
'myalgias (myalgia)':'muscle pain',
'pains, muscle (myalgia)':'muscle pain',
'spasm (muscle cramp)':'muscle pain',
'tender muscles (muscle tenderness)':'muscle pain',
'tender muscles (skeletal muscle tender)':'muscle pain',
'walking pain':'muscle pain',
'cervical pain (neck pain)':'neck pain',
'discomfort neck (neck discomfort)':'neck pain',
'neck discomfort':'neck pain',
'neck pain':'neck pain',
'neck pain (neck pain)':'neck pain',
'neck shoulder pain (pain neck/shoulder)':'neck pain',
'neck spasm (neck cramps)':'neck pain',
'neck tightness':'neck pain',
'pain in neck (neck pain)':'neck pain',
'pain neck (neck pain)':'neck pain',
'pain radiating to neck':'neck pain',
'posterior neck pain (posterior cervical pain)':'neck pain',
'neuralgia':'neuropathic pain',
'neuropathic pain (neuralgia)':'neuropathic pain',
'painless haematuria (painless hematuria)':'no pain',
'mouth pain (oral pain)':'oral pain',
'oral pain':'oral pain',
'oral pain (pain of oral cavity structure)':'oral pain',
'acute onset pain':'pain',
'acute pain (acute onset pain)':'pain',
'after pain (after pains)':'pain',
'catch (catch - finding of sensory dimension of pain)':'pain',
'catching (catch - finding of sensory dimension of pain)':'pain',
'central pain':'pain',
'depression pain (miserable pain)':'pain',
'diffuse pain':'pain',
'discomfort (discomfort)':'pain',
'discomfort (malaise)':'pain',
'discomfort (sensory discomfort)':'pain',
'dolor (pain)':'pain',
'general pain (generalized aches and pains)':'pain',
'generalized pain (generalized aches and pains)':'pain',
'intermittent pain':'pain',
'localized pain':'pain',
'nerve pain':'pain',
'night pain':'pain',
'non specific pain (pain)':'pain',
'pain':'pain',
'pain (pain)':'pain',
'pain at injection site (injection site pain)':'pain',
'pain at rest (rest pain)':'pain',
'pain night (night pain)':'pain',
'pain radiating (radiating pain)':'pain',
'pain symptoms (pain)':'pain',
'pain with swallowing (swallowing painful)':'pain',
'pain, postoperative':'pain',
'pain, referred':'pain',
'painful (pain)':'pain',
'pains (pain)':'pain',
'peripheral neuropathic pain':'pain',
'post-op pain (pain, postoperative)':'pain',
'post-procedural pain':'pain',
'pulsatile pain (throbbing pain)':'pain',
'radiating pain':'pain',
'radicular pain':'pain',
'rest pain':'pain',
'sciatic nerve pain':'pain',
'tender scar':'pain',
'tenderness (nos) (sore to touch)':'pain',
'total body pain (total body pain syndrome)':'pain',
'transplant pain':'pain',
'types of pain (pain)':'pain',
'wound pain':'pain',
'wound tenderness':'pain',
'abdominal pelvic pain (abdominal and pelvic pain)':'pelvic pain',
'chronic pelvic pain (chronic pelvic pain of female)':'pelvic pain',
'pelvic pain':'pelvic pain',
'pelvic pain (pelvic pain female)':'pelvic pain',
'pelvic pain (pelvic pain)':'pelvic pain',
'pelvic pain, nos (pelvic pain female)':'pelvic pain',
'pelvis pain (pelvic pain)':'pelvic pain',
'pubic pain':'pelvic pain',
'sacroiliac pain (sacroiliac pain)':'pelvic pain',
'discomfort rectal':'rectal pain',
'rectal discomfort (discomfort rectal)':'rectal pain',
'rectal pain':'rectal pain',
'costovertebral angle tenderness (renal angle tenderness)':'renal pain',
'cva tenderness (renal angle tenderness)':'renal pain',
'kidney pain (renal pain)':'renal pain',
'retrosternal chest pain (retrosternal pain)':'retrosternal pain',
'substernal chest pain (retrosternal pain)':'retrosternal pain',
'substernal pain (retrosternal pain)':'retrosternal pain',
'lower rib pain (lower ribs pain)':'rib pain',
'rib pain':'rib pain',
'scalp tenderness':'scalp tenderness',
'unbearable pain':'scalp tenderness',
'scrotal pain (pain in scrotum)':'scrotal tenderness',
'scrotal tenderness':'scrotal tenderness',
'scrotum tenderness (scrotal tenderness)':'scrotal tenderness',
'breakthrough pain':'severe pain',
'deep pain':'severe pain',
'dull pain':'severe pain',
'excruciating pain':'severe pain',
'pain throbbing (throbbing pain)':'severe pain',
'pain trigger (pain characterized by provoking factor)':'severe pain',
'pain uncontrolled':'severe pain',
'pain worsening (pain aggravated)':'severe pain',
'severe pain':'severe pain',
'throbbing pain':'severe pain',
'bursal pain':'shoulder pain',
'pain in left shoulder':'shoulder pain',
'pain in right shoulder':'shoulder pain',
'pain in right shoulder (pain of right shoulder joint)':'shoulder pain',
'pain in scapula (scapulalgia)':'shoulder pain',
'pain in shoulder (shoulder pain)':'shoulder pain',
'pain radiating to left shoulder':'shoulder pain',
'pain radiating to right shoulder':'shoulder pain',
'pain right shoulder (pain in right shoulder)':'shoulder pain',
'scapular pain (scapulalgia)':'shoulder pain',
'shoulder discomfort':'shoulder pain',
'shoulder pain':'shoulder pain',
'shoulder pain (shoulder pain)':'shoulder pain',
'shoulder pain, left (pain in left shoulder)':'shoulder pain',
'shoulder pain, left (pain of left shoulder joint)':'shoulder pain',
'shoulder pain, right (pain in right shoulder)':'shoulder pain',
'shoulder pain, right (pain of right shoulder joint)':'shoulder pain',
'shoulder tenderness':'shoulder pain',
'skin pain (pain of skin)':'skin pain',
'superficial pain':'skin pain',
'pain soreness (pain and tenderness)':'sore',
'pain tenderness (pain and tenderness)':'sore',
'sore (sore skin)':'sore',
'sore (sore to touch)':'sore',
'soreness (sore to touch)':'sore',
'tenderness (sore to touch)':'sore',
'sore mouth':'sore mouth',
'pain throat (sore throat)':'sore throat',
'sore throats (sore throat)':'sore throat',
'sorethroat (sore throat)':'sore throat',
'throat discomfort (sore throat)':'sore throat',
'throat pain (sore throat)':'sore throat',
'esophageal pain (pain in esophagus (finding))':'stomach pain',
'stomach discomfort (upset stomach)':'stomach pain',
'stomach pain (stomach ache)':'stomach pain',
'subcostal pain':'subcostal pain',
'sharp pain':'sudden pain',
'sharp pain (sharp pain)':'sudden pain',
'shooting pain':'sudden pain',
'stabbing pain':'sudden pain',
'stabbing pain (stabbing pain)':'sudden pain',
'sudden onset pain (acute onset pain)':'sudden pain',
'sudden pain (acute onset pain)':'sudden pain',
'odynophagia (swallowing painful)':'swallowing painful',
'pain swallowing (swallowing painful)':'swallowing painful',
'pain with eating':'swallowing painful',
'tendon tenderness (tenderness of tendon)':'tendon tenderness',
'great toe pain':'toe pain',
'toe pain (pain in toe)':'toe pain',
'dental pain (toothache)':'toothache',
'tooth pain (toothache)':'toothache',
'toothaches (toothache)':'toothache',
'umbilical pain':'umbilical pain',
'vascular pain':'vascular pain',
'stomachaches (upset stomach)':'wrist pain',
'wrist pain (pain in wrist)':'wrist pain',
}

pain_terms = ['ache', 'aching', 'angina', 'arthralgia', 'arthrodynia', 'burning', 'cephalalgia', 'cephalgia',
                  'cephalodynia', 'cervicalgia', 'cervicodynia', 'claudication', 'coccyalgia', 'coccydynia',
                  'coccygalgia', 'coccygodynia', 'coccyodynia', 'coccyxdynia', 'coxalgia', ' cp ', 'cramp',
                  'discomfort', 'dolor', 'dorsalgia', 'dorsodynia', 'dysuria', 'esophagodynia', 'glossalgia',
                  'glossalgias', 'glossodynia', 'glossodynias', 'gonalgia', 'inguinodynia', 'lbp', 'lowbacksyndrome',
                  'lumbago', 'lumbagoambiguous', 'lumbalgia', 'meralgia', 'metatarsalgia', 'muscleweakness',
                  'myalgia', 'myalgias', 'myodynia', 'myosalgia', 'neuralgia', 'neuralgias', 'odynophagia',
                  'orchialgia', 'orchidalgia', 'orchidodynia', 'osteodynia', 'otalgia', 'pain', 'pancreatalgia',
                  'postherpeticneuralgia', 'postherpeticneuralgia', 'pressure', 'proctalgia', 'rectalgia',
                  'retrosternal', 'scapulalgia', 'scapulodynia', 'sciatica', 'sore', 'tender', 'tightness', 
                 ]
